---
# "Include" for unit tests definition.
unit_tests: &unit_tests
  steps:
    - checkout
    - run:
        name: Install modules and dependencies.
        command: npm install
    - run:
        name: Run unit tests.
        command: npm test

version: 2.0
workflows:
  version: 2
  tests:
    jobs:
      - node8
      - node10
      - node11
      - publish_npm:
          requires:
            - node8
            - node10
            - node11
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[\d.]+$/

jobs:
  node8:
    docker:
      - image: node:8
    <<: *unit_tests
  node10:
    docker:
      - image: node:10
    <<: *unit_tests
  node11:
    docker:
      - image: node:11
    <<: *unit_tests

  publish_npm:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: Set NPM authentication.
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
         name: Publish the module to npm.
         command: npm publish
