on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: GoogleCloudPlatform/release-please-action@v2
        with:
          token: ${{ secrets.YOSHI_AUTOMATION_TOKEN }}
          release-type: node
          package-name: eventid
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 14
          registry-url: 'https://wombat-dressing-room.appspot.com'
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - run: npm run compile
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
